---
- name: Install and Deploy WAR to Tomcat on Amazon Linux
  hosts: webservers
  become: yes

  vars:
    tomcat_dir: /opt/tomcat
    tomcat_webapps: /opt/tomcat/webapps

  tasks:

  - name: Install Java
    yum:
      name: java-11-amazon-corretto
      state: present

  - name: Install wget
    yum:
      name: wget
      state: present

  - name: Download Tomcat
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.85/bin/apache-tomcat-9.0.85.tar.gz
      dest: /tmp/tomcat.tar.gz

  - name: Extract Tomcat
    unarchive:
      src: /tmp/tomcat.tar.gz
      dest: /opt/
      remote_src: yes

  - name: Rename Tomcat directory
    command: mv /opt/apache-tomcat-9.0.85 {{ tomcat_dir }}
    args:
      creates: "{{ tomcat_dir }}"

  - name: Start Tomcat
    shell: "{{ tomcat_dir }}/bin/startup.sh"

  - name: Copy WAR file
    copy:
      src: "{{ artifact }}"
      dest: "{{ tomcat_webapps }}/devops.war"
      remote_src: yes

  - name: Restart Tomcat
    shell: |
      {{ tomcat_dir }}/bin/shutdown.sh
      sleep 5
      {{ tomcat_dir }}/bin/startup.sh
